import re, sys, subprocess
from pathlib import Path
import streamlit as st
import pandas as pd
ROOT = Path(__file__).parent.resolve()

def run_predict(model_pt: str, tag: str, rec65: str, rec115: str, force_probe: bool):
    cmd = [
        sys.executable, str(ROOT / "predict_batch_size.py"),
        "--model", model_pt,
        "--tag", tag,
        "--rec65", rec65,
        "--rec115", rec115,
        "--force_probe", "1" if force_probe else "0",
    ]
    proc = subprocess.run(cmd, cwd=str(ROOT), capture_output=True, text=True)
    return proc.returncode, proc.stdout, proc.stderr

def parse_predictions(stdout: str):
    rows = []
    in_block = False
    for line in stdout.splitlines():
        if "Predictions (W / mAP50)" in line:
            in_block = True
            continue
        if in_block:
            if line.strip().startswith("Best batch size"):
                break
            m = re.match(r"^[\s\*]+b(\d+)\s+([\d\.]+)\s*W\s+([\d\.]+)", line.strip())
            if m:
                b = int(m.group(1)); pw = float(m.group(2)); mp = float(m.group(3))
                rows.append((b, pw, mp))
    best = None
    m2 = re.search(r"Best batch size.*?:\s*(\d+)", stdout)
    if m2:
        best = int(m2.group(1))
    df = pd.DataFrame(rows, columns=["batch", "avg_power_pred_W", "mAP50_pred"])
    return df, best

def main():
    st.set_page_config(page_title="YOLO Batch Size Recommender", layout="wide")

    st.title("Predict Best Batch Size for This Computer")
    st.caption("Uses your existing `predict_batch_size.py` (table+probe) with {2,4,8,16} candidates and δmAP=1%.")
    colA, colB, colC = st.columns([1,1,1])
    with colA:
        model_pt = st.text_input("YOLO weights (.pt)", value="yolo11n.pt")
    with colB:
        tag = st.selectbox("Power tag", options=["auto", "65W", "115W"], index=0)
    with colC:
        force_probe = st.checkbox("Force probe (run b=1 once)", value=False)

    with st.expander("Advanced", expanded=False):
        rec65 = st.text_input("Recommendations (65W)", value=str(ROOT / "scripts/outputs/recommendations_65W_constrained.csv"))
        rec115 = st.text_input("Recommendations (115W)", value=str(ROOT / "scripts/outputs/recommendations_115W_constrained.csv"))
        st.caption("These are generated by `scripts/infer_ranker_table.py`.")
    if st.button("Predict best batch size for this computer", type="primary"):
        with st.spinner("Running predict_batch_size.py ..."):
            code, out, err = run_predict(model_pt, tag, rec65, rec115, force_probe)
        if code != 0:
            st.error("predict_batch_size.py failed.")
            st.code(err or out, language="bash")
            return

        df, best = parse_predictions(out)
        st.subheader("Prediction summary")
        if best is not None:
            st.success(f"Best batch size (≤1% drop): **{best}**")
        else:
            st.warning("Could not parse best batch size from output.")

        if not df.empty:
            st.dataframe(df, use_container_width=True)
        with st.expander("Raw console output"):
            st.code(out, language="bash")
        if not df.empty and best in df["batch"].values:
            pw = float(df.loc[df["batch"]==best, "avg_power_pred_W"].iloc[0])
            st.session_state["footprint_power_W"] = pw

    st.markdown("---")
    st.header("Explainability")
    shap_dir = st.text_input("SHAP figures directory", value=str(ROOT / "scripts/outputs/shap_v7_run2"))
    colX, colY = st.columns(2)
    with colX:
        p = Path(shap_dir) / "shap_bar.png"
        if p.exists():
            st.image(str(p), caption="SHAP Bar (mean|SHAP|)")
        else:
            st.info(f"Not found: {p}")
    with colY:
        p = Path(shap_dir) / "shap_beeswarm.png"
        if p.exists():
            st.image(str(p), caption="SHAP Beeswarm")
        else:
            st.info(f"Not found: {p}")

    st.markdown("---")
    st.header("Footprint (quick estimate)")
    col1, col2, col3, col4 = st.columns(4)
    with col1:
        region = st.selectbox("Region", ["UK (2024)", "CN (H1 2025)"], index=0)
    with col2:
        default_g = 124.0 if region.startswith("UK") else 492.0
        g_per_kwh = st.number_input("Grid intensity (gCO₂/kWh)", value=default_g, step=1.0)
    with col3:
        power_W = st.number_input("Average power of chosen batch (W)",
                                  value=float(st.session_state.get("footprint_power_W", 30.0)), step=1.0)
    with col4:
        secs = st.number_input("Training duration (sec)", value=60, step=10)

    kwh = power_W * secs / 3600.0 / 1000.0
    co2_g = kwh * g_per_kwh
    st.metric("Estimated CO₂ (grams)", f"{co2_g:.1f}")
    st.caption("Formula: kWh = W×s / 3,600,000; CO₂ = kWh × gCO₂/kWh.")

    st.markdown("---")
    st.caption("© Your MSc Project — uses existing scripts: predict_batch_size.py / tag_detect.py / recommendations_*.csv")

if __name__ == "__main__":
    main()
